---
resources:
- name: spring-boot-sample
  type: git
  source:
    uri: https://github.com/kassytech01/spring-boot-sample.git
    branch: master

- name: version
  type: semver
  source:
    bucket: tkasuga-concourse-s3
    key: current-version
    access_key_id: AKIAILSWR2YH5MCOFH7A
    secret_access_key: 45x4rbvJElveDHRaaIgugDa5H3yun9Oi0szfORTz
    initial_version: 1.0.0

- name: s3-artifact-rc
  type: s3
  source:
    bucket: tkasuga-concourse-s3
    regexp: my-product-(.*).tgz
    access_key_id: AKIAILSWR2YH5MCOFH7A
    secret_access_key: 45x4rbvJElveDHRaaIgugDa5H3yun9Oi0szfORTz

jobs:
- name: build-rc
  serial_groups: [version]
  plan:
  - get: spring-boot-sample
    trigger: true
  - get: version
    params: {pre: rc}
  - task: build-artifact
    file: spring-boot-sample/ci/gradle-build.yml
  - put: s3-artifact-rc
    params: {file: build/libs/my-product-*.tgz}
  - put: version
    params: {file: version/version}
